## NumPy
1. NumPy is the short form of Numerical Python
2. NumPy is apackage that defines a multi-dimension array object and associates fast math funcions that operate on
3. It also has functions for working in domain of linear algebra,fourier Transformaions and Matrices.
4. In simple words it is the fundamental package of scientific computing in python.

### Arrays
1. An array is definde as a collection of items that are stored at contiguous memory locations.
2. It is a container which can hold a fixed number of items and these items should be of the same type.
3. A combination of array saves a lot of time. The array can reduce the overall size of the code.

##### Advatages of array
1. Numpy uses much less memory to store data.
2. Numpy makes it extremely easy to perform mathematical operations on it.
3. Used for the creation of n-dimensional array.
4. Finding elements in Numpy array is easy.
5. A list cannot directly handle mathematical operations, while array can.
6. An Array consoumes less memory then a list.
7. Using an array is faster than list.
8. A list can store different datatypes, while you can't do that it an Array.


#### Arrays vs Lists
1. A list cannot directly handle mathematical operations while array can.
2. An array consumes less memory than a list
3. Using an array is faster than list.
4. A list can store different datatypes while you can't do that in a array
5. A list is easier to modify since a list store each element individually it is easier to add and delets and element than an array does.
6. In list one can have nested data with different size while you cannot do the same in array.

In [1]:
## if you add or multiplication two list it not perform mathmatical operations
# but numpy array perform mathematical operations

In [2]:
## for list             {its result value are coma separate}

l1 = [20,30,40,50]
l2 = [30,40,20,10]
print(l1)
print(l2)
print(l1 + l2)


[20, 30, 40, 50]
[30, 40, 20, 10]
[20, 30, 40, 50, 30, 40, 20, 10]


In [3]:
## same value for numpy arrar    {its result value are not coma separate}

import numpy as np

a = np.array([20,30,40,50])
b = np.array([30,40,20,10])
print(a)
print(b)
print(a+b)


[20 30 40 50]
[30 40 20 10]
[50 70 60 60]


In [4]:

a = np.array([20,30,40,50])
b = np.array([10])
print(a)
print(b)
print(a * b)


[20 30 40 50]
[10]
[200 300 400 500]


In [5]:
l2 = [[30,40,20,10],[20,30,10]]
print(l2)

[[30, 40, 20, 10], [20, 30, 10]]


In [6]:
# this code show an error because array size are not same

b = np.array([[30,40,20,10],[20,30,10]])
print(b)


[list([30, 40, 20, 10]) list([20, 30, 10])]


C:\Users\Prince\AppData\Local\Temp\ipykernel_11300\3886460977.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[30,40,20,10],[20,30,10]])


### NumPy - creating arrays, slicing and attributes

In [7]:
import numpy as np

In [8]:
arr = np.array([10,20,30,40,500])
print(arr)
print(type(arr))

[ 10  20  30  40 500]
<class 'numpy.ndarray'>


In [9]:
arr = np.array([[10,20,30,40],[20,30,50,60],[60,30,40,70]])
print(arr)
print(type(arr))

[[10 20 30 40]
 [20 30 50 60]
 [60 30 40 70]]
<class 'numpy.ndarray'>


In [10]:

arr = np.array([10,20,30,40,500])
print(arr[0:3])
print(arr[:])
print(arr[2:])

[10 20 30]
[ 10  20  30  40 500]
[ 30  40 500]


In [11]:
arr = np.array([[10,20,30,40],[20,30,50,60]])
print(arr[0:2,0:2])
print(arr[0:2,0:3])


[[10 20]
 [20 30]]
[[10 20 30]
 [20 30 50]]


In [38]:
arr = np.array([[10,20,30,40],[20,30,50,60],[60,30,40,70]])
print(arr[0,0:3])
print(arr[1,2:])
print(arr[2,3])


[10 20 30]
[50 60]
70


##### Attributes an array

In [39]:
arr = np.array([[10,20,30,40],[20,30,50,60],[60,30,40,70]])
print(np.shape(arr))


(3, 4)


In [40]:
arr = np.array([[10,20,30,40],[20,30,50,60],[60,30,40,70]])
print(np.size(arr))


12


In [41]:
arr = np.array([[10,20,30,40],[20,30,50,60],[60,30,40,70]])
print(np.ndim(arr))  # nd means data dimention
 

2


In [43]:
arr = np.array([[10,20,30,40],[20,30,50,60],[60,30,40,70]])
print(arr.dtype)


int32


### Functions an array
1. arr.shape - Array dimensions
2. len(arr) - Length of array
3. b.ndim - Number of array dimensions
4. np.size - Number of array elements
5. b.dtype - Data type of array elements
6. b.astype(int) - Convert on array to a different type


In [45]:
import numpy as np

a = [30,50,40,60,30]
arr = np.array(a)
print(arr)
print(arr.shape)

[30 50 40 60 30]
(5,)


In [58]:
## shape - rows and columns

a = [[30,50,40,60,30],[20,30,10,80,90]]
arr = np.array(a)
print(arr)
print(arr.shape)     #{ The number of row are two and column are five }

[[30 50 40 60 30]
 [20 30 10 80 90]]
(2, 5)


In [48]:
a = [[30,50,40,60,30],[20,30,10,80,90]]
arr = np.array(a)
print(len(arr))


2


In [50]:
a = [[30,50,40,60,30],[20,30,10,80,90]]
print(np.size(arr))


10


In [51]:
a = [[30,50,40,60,30],[20,30,10,80,90]]
arr = np.array(a)
print(type(arr))


<class 'numpy.ndarray'>


In [52]:
a = [[30,50,40,60,30],[20,30,10,80,90]]
arr = np.array(a)
print(arr.dtype)


int32


In [56]:
a = [[30,50,40,60,30],[20,30,10,80,90]]
arr = np.array(a)
print(arr)
print(arr.astype(float))
print(arr.astype(str))

[[30 50 40 60 30]
 [20 30 10 80 90]]
[[30. 50. 40. 60. 30.]
 [20. 30. 10. 80. 90.]]
[['30' '50' '40' '60' '30']
 ['20' '30' '10' '80' '90']]


In [57]:
a = [[30.12,50,40,60,30],[20,30,10,80,90]]
arr = np.array(a)
print(arr)
print(arr.astype(int))


[[30.12 50.   40.   60.   30.  ]
 [20.   30.   10.   80.   90.  ]]
[[30 50 40 60 30]
 [20 30 10 80 90]]


### Mathematical Operations and functions on arrays

In [3]:
import numpy as np

arr1 = np.array([30,50,40,60,30])
arr2 = np.array([20,30,10,80,90])
print(arr1+arr2)


[ 50  80  50 140 120]


In [6]:
import numpy as np

arr1 = np.array([30,50,40,60,30])
arr2 = np.array([20,30,10,80,90])
print(np.add(arr1,arr2))


[ 50  80  50 140 120]


In [8]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(arr1+arr2)


[[ 50  80]
 [ 50 140]]


In [7]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(np.add(arr1,arr2))


[[ 50  80]
 [ 50 140]]


In [9]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(arr1-arr2)

[[ 10  20]
 [ 30 -20]]


In [11]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(np.subtract(arr1,arr2))

[[ 10  20]
 [ 30 -20]]


In [12]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(arr1*arr2)

[[ 600 1500]
 [ 400 4800]]


In [13]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(np.multiply(arr1,arr2))


[[ 600 1500]
 [ 400 4800]]


In [14]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(arr1/arr2)


[[1.5        1.66666667]
 [4.         0.75      ]]


In [15]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])
print(np.divide(arr1,arr2))


[[1.5        1.66666667]
 [4.         0.75      ]]


In [18]:
##  power

import numpy as np

arr1 = np.array([[3,5,4,6]])
arr2 = np.array([3])

print(np.power(arr1,arr2))    ##{ (3 power 3),(5 power 3),(4 power 3),(6 power 3)}


[[ 27 125  64 216]]


In [20]:
## sqrt

import numpy as np

arr1 = np.array([25,16,4,1])
print(np.sqrt(arr1))


[5. 4. 2. 1.]


#### Combining and Splitting Arrays

In [22]:
## for list

arr1 = [30,50,40,60,30]
arr2 = [20,30,10,80,90]

print(arr1+arr2)


[30, 50, 40, 60, 30, 20, 30, 10, 80, 90]


In [23]:
## for array we use concatenate

import numpy as np

arr1 = np.array([30,50,40,60,30])
arr2 = np.array([20,30,10,80,90])

print(np.concatenate([arr1,arr2]))


[30 50 40 60 30 20 30 10 80 90]


In [26]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])

print(np.concatenate([arr1,arr2],axis = 0))   ## “axis 0” represents rows 


[[30 50]
 [40 60]
 [20 30]
 [10 80]]


In [ ]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])

print(np.vstack([arr1,arr2]))   ## vertical concatenation ( vstack = vertical stack)

In [29]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])

print(np.concatenate([arr1,arr2],axis = 1))  ## “axis 1” represents columns


[[30 50 20 30]
 [40 60 10 80]]


In [28]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
arr2 = np.array([[20,30],[10,80]])

print(np.hstack([arr1,arr2]))   ## horizontal concatenation ( hstack = horizontal stack)


[[30 50 20 30]
 [40 60 10 80]]


In [35]:
import numpy as np

arr1 = np.array([30,50,40,60,30])
print(np.array_split(arr1,3))     # arr1 divide three part

b = np.array_split(arr1,3)
print(b[1])
print(b[1])


[array([30, 50]), array([40, 60]), array([30])]
[40 60]
[40 60]


In [38]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
b = np.array_split(arr1,2)
print(b)


[array([[30, 50]]), array([[40, 60]])]


In [39]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
b = np.array_split(arr1,3)
print(b)


[array([[30, 50]]), array([[40, 60]]), array([], shape=(0, 2), dtype=int32)]


### Adding and Removing elements in the arrays
1. np.append - Append items to an array
2. np.insert - Inserts items in an array
3. np.delete - Delete items from an array

In [44]:
## append

import numpy as np


arr1 = np.array([30,50,40,60,30])
print(np.append(arr1,90))


[30 50 40 60 30 90]


In [46]:
import numpy as np


arr1 = np.array([30,50,40,60,30])
print(np.append(arr1,[90,70]))


[30 50 40 60 30 90 70]


In [45]:
import numpy as np

arr1 = np.array([[30,50],[40,60]])
print(np.append(arr1,80))


[30 50 40 60 80]


In [47]:
## insert

arr1 = np.array([30,40,60,70,80])
print(np.insert(arr1,2,50))       # first array, second index, third value
 

[30 40 50 60 70 80]


In [49]:

arr1 = np.array([[30,50],[40,60]])
print(np.insert(arr1,2,[51,55])) 


[30 50 51 55 40 60]


In [51]:

arr1 = np.array([[30,50],[40,60]])
print(np.insert(arr1,2,[51,55], axis = 0)) 


[[30 50]
 [40 60]
 [51 55]]


In [50]:

arr1 = np.array([[30,50],[40,60]])
print(np.insert(arr1,2,[51,55], axis = 1)) 


[[30 50 51]
 [40 60 55]]


In [53]:

arr1 = np.array([[30,50],[40,60]])
print(np.insert(arr1,2,[55], axis = 0))  ## If value is single


[[30 50]
 [40 60]
 [55 55]]


In [54]:

arr1 = np.array([[30,50],[40,60]])
print(np.insert(arr1,1,[55], axis = 0))  ## If value is single


[[30 50]
 [55 55]
 [40 60]]


In [56]:

arr1 = np.array([[30,50],[40,60]])
print(np.insert(arr1,[1,2],[55], axis = 0))  ## If value is single


[[30 50]
 [55 55]
 [40 60]
 [55 55]]


In [58]:
## delete

arr1 = np.array([30,40,60,70,80])
print(arr1)
print(np.delete(arr1,1))


[30 40 60 70 80]
[30 60 70 80]


In [59]:

arr1 = np.array([30,40,60,70,80])
print(arr1)
print(np.delete(arr1,[1,2]))


[30 40 60 70 80]
[30 70 80]


In [60]:

arr1 = np.array([[30,50],[40,60]])
print(arr1)
print('\n')
print(np.delete(arr1,1))


[[30 50]
 [40 60]]


[30 40 60]


In [61]:

arr1 = np.array([[30,50],[40,60]])
print(arr1)
print('\n')
print(np.delete(arr1,1, axis = 0))


[[30 50]
 [40 60]]


[[30 50]]


In [62]:

arr1 = np.array([[30,50],[40,60]])
print(arr1)
print('\n')
print(np.delete(arr1,0, axis = 0))


[[30 50]
 [40 60]]


[[40 60]]


In [64]:

arr1 = np.array([[30,50],[40,60]])
print(arr1)
print('\n')
print(np.delete(arr1,0, axis = 1))


[[30 50]
 [40 60]]


[[50]
 [60]]


In [65]:

arr1 = np.array([[30,50],[40,60]])
print(arr1)
print('\n')
print(np.delete(arr1,1, axis = 1))


[[30 50]
 [40 60]]


[[30]
 [40]]


### Sort, filter and Search

In [66]:
## sort

arr1 = np.array([50,5,20,70,10,70,30,7])
print(np.sort(arr1))


[ 5  7 10 20 30 50 70 70]


In [5]:
# search

import numpy as np

arr1 = np.array([50,5,20,70,10,70,30,7])
a = np.where(arr1 == 5)  # index of 5
print(a)


(array([1], dtype=int64),)


In [7]:
# search

import numpy as np

arr1 = np.array([50,5,20,70,10,70,30,7])
a = np.where(arr1 % 2 == 0)  # find the index which is divide 2
print(a)


(array([0, 2, 3, 4, 5, 6], dtype=int64),)


In [12]:
# another way of search (it find the index of sorted value)

import numpy as np

arr1 = np.array([1,2,3,4,5,6])
a = np.searchsorted(arr1,4)
print(a)


3


In [14]:
## filter

import numpy as np

arr = np.array([50,20,70,10,70,30])

filte = [True, True, False, False, False, True]
new_array = arr[filte]
print(new_array)


[50 20 30]


In [15]:
## filter

import numpy as np

arr = np.array([50,20,70,10,70,30])

filte = arr>45

new_array = arr[filte]
print(new_array)


[50 70 70]


In [19]:
## filter

import numpy as np

arr = np.array([17,50,20,5,70,10,70,30])

filte = (arr % 2 == 0)

new_array = arr[filte]
print(new_array)


[50 20 70 10 70 30]


### Aggregating functions in NumPy

In [20]:
import numpy as np

arr = np.array([17,50,20,5,70,10,70,30])
print(np.sum(arr))


272


In [21]:
import numpy as np

arr = np.array([17,50,20,5,70,10,70,30])
print(np.min(arr))


5


In [22]:
import numpy as np

arr = np.array([17,50,20,5,70,10,70,30])
print(np.max(arr))


70


In [23]:
import numpy as np

arr = np.array([17,50,20,5,70,10,70,30])
print(np.size(arr))


8


In [24]:
import numpy as np

arr = np.array([17,50,20,5,70,10,70,30])
print(np.mean(arr))


34.0


In [26]:
import numpy as np

arr = np.array([10,50,20,5,70,10,70,30])
print(np.cumsum(arr))

## Cumulative sum, is a sequence of partial sums of a given data set
## [{10+50=60} {60+20=80} {80+85=155}...............]

[ 10  60  80  85 155 165 235 265]


In [27]:
import numpy as np

arr = np.array([10,50,20,5,70,10,70,30])
print(np.cumprod(arr))


[         10         500       10000       50000     3500000    35000000
 -1844967296   485555968]


In [36]:
a = [100,150,199,200,250,180]
b = [10,30,25,15,18,20]

price = np.array(a)
quantity = np.array(b)

print(price, '\n', quantity)
print()
c = np.cumprod([price,quantity], axis = 0)
print(c)
print()

print(c[1])
print("Total sum is -",c[1].sum())


[100 150 199 200 250 180] 
 [10 30 25 15 18 20]

[[ 100  150  199  200  250  180]
 [1000 4500 4975 3000 4500 3600]]

[1000 4500 4975 3000 4500 3600]
Total sum is - 21575


### Statistical funcions NumPy

In [44]:
import numpy as np
import statistics as sta

baked_food = [200,250,150,130,280,270,170,130]
arr = np.array(baked_food)

print(np.mean(baked_food))
print()
print(np.median(baked_food))
print()
print(sta.mode(baked_food))
print()
print(np.std(baked_food))    # we use standar deviation for quality control
print()
print(np.var(baked_food))


197.5

185.0

130

58.0409338312195

3368.75


In [45]:
## Correlation Coefficient

# -1 represent inversely proportional relationship
# 1 represent porportional relationship
# 0 means no relationship

tobacco_consumption = [30,40,20,10,50,25]
deaths = [150,160,130,70,140,135]

print(np.corrcoef([tobacco_consumption,deaths]))


[[1.         0.74170034]
 [0.74170034 1.        ]]


In [47]:
## negative relationship

price = [300,100,350,150,200]
sales = [10,20,7,17,3]

print(np.corrcoef(price,sales))


[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
